### ISSUE TITLE
Add support for missing libm functions

### ISSUE THREAD

**Issue by overdrivenpotato** [overdrivenpotato/rust-psp#105]
The following code will not compile due to a link error, as `fmodf` is missing:

```rust
fn psp_main() {
    psp::dprintln!("{}", 10f32 % core::hint::black_box(2.0));
}
```

This can likely be resolved by linking in the [`libm` crate](https://crates.io/crates/libm), which has an [implementation of `fmodf`](https://docs.rs/libm/0.2.1/libm/fn.fmodf.html). This should fix any additional missing functions.

Alternatively it may be possible to somehow natively compile this, if the PSP can support such an instruction (perhaps even through VFPU). This would result in much faster code.

**Comment by overdrivenpotato** [comment]
Initially discovered in #102

**Comment by sajattack** [comment]
I don't think vfpu has any instructions for modulus.

**Comment by sajattack** [comment]
fminf/fmaxf as well (used by fontdue)

**Comment by Lucky4Luuk** [comment]
How is this coming along? Like sajattack, a library I would like to use, uses fminf/fmaxf :p
