### ISSUE TITLE
Unable to compile hello world

### ISSUE THREAD

**Issue by Beyley** [overdrivenpotato/rust-psp#110]
whenever i attempt to compile any of the example applications, it errors out, i tried the steps in [this comment](https://github.com/overdrivenpotato/rust-psp/issues/108#issuecomment-994887964) but that did not seem to help

[error.log](https://github.com/overdrivenpotato/rust-psp/files/8038035/error.log)

Edit: If i downgrade to toolchain version to nightly-2021-11-17 it works fine, so it seems to be from the newer nightlies

**Comment by sajattack** [comment]
Yes, llvm_asm was removed from rust it seems, we're working on upgrading to the new asm macro.

**Comment by overdrivenpotato** [comment]
Fixed in 7092d10, released as breaking change in `psp = "0.2.0"`
