### ISSUE TITLE
Core support

### ISSUE THREAD

**Issue by Lucky4Luuk** [overdrivenpotato/rust-psp#111]
In the README it mentions core support.
Doing `cargo psp -Z build-std=core` fails, however, and so does `cargo psp -Z build-std=core,alloc` (without alloc, I get a few more errors about alloc not being available, I imagine to use core I also have to enable the alloc crate).
I'm using the latest version of the library, with the `embedded-graphics` feature enabled.

I get the following error:
```
error[E0463]: can't find crate for `panic_unwind`
  --> C:\Users\luukv\.cargo\registry\src\github.com-1ecc6299db9ec823\psp-0.2.1\src\lib.rs:25:36
   |
25 | #[cfg(not(feature = "stub-only"))] extern crate panic_unwind;
   |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: language item required, but not found: `eh_personality`
  |
  = note: this can occur when a binary crate with `#![no_std]` is compiled for a target where `eh_personality` is defined in the standard library
  = help: you may be able to compile for a target that doesn't need `eh_personality`, specify a target with `--target` or in `.cargo/config`
```

Any idea what this means?

**Comment by overdrivenpotato** [comment]
It looks like you're overriding the flags that `cargo psp` provides to cargo. By default, running `cargo psp` will build `core`, along with `panic_unwind`, etc, fixing those errors.

Try running just `cargo psp` instead without the flags.

**Comment by Lucky4Luuk** [comment]
I see. When I was not trying to build core myself, I got an error from a no_std library (glam) that core was missing, so I figured I had to enable it myself.

**Comment by overdrivenpotato** [comment]
Out of curiosity, were you able to get a PSP project to build with glam as a dependency?

**Comment by Lucky4Luuk** [comment]
I did not manage to build it with glam, without glam everything was fine. I'll do some more testing tomorrow, otherwise I'll just pick a different math library :)

**Comment by Lucky4Luuk** [comment]
Other no_std libraries seem to work fine (I couldn't resist testing some more today), must be because glam is a little weird in no_std.

**Comment by sajattack** [comment]
Nice! Yeah glam would probably need some extra work. I've messed with fontdue and hecs, oddio should work too but hasn't been tested.
