### ISSUE TITLE
How to draw sprites to display without embedded graphics?

### ISSUE THREAD

**Issue by imagineeeinc** [overdrivenpotato/rust-psp#141]
I am trying to make a game where I need to display sprites to the screen, I followed a tutorial to setup a graphics system, but can't seem to draw sprites, If anyone can point me in the right direction to set up.

**Comment by sajattack** [comment]
You'll want to use sceGu. I wrote a sprite engine that uses sceGu in this example https://github.com/overdrivenpotato/rust-psp/blob/master/examples/fontdue-scrolltext/src/graphics/sprite.rs

**Comment by sajattack** [comment]
If you need more help, feel free to join the #rust-psp channel in the PSP homebrew discord and I'll try to walk you through it https://discord.gg/WY8XhDG
