### ISSUE TITLE
How to send HTTP requests?

### ISSUE THREAD

**Issue by lorenzofelletti** [overdrivenpotato/rust-psp#147]
Is there a way to send HTTP requests with this crate?
I would really like to, but can't figure out how.
Can somebody please help me?

**Comment by sajattack** [comment]
There's a simpler example here that just yeets some bytes over a TCP socket https://github.com/sajattack/rust-psp/blob/centronian/examples/centronian/src/main.rs
If you combine the get request from tls-test and the socket code from centronian you will have plain HTTP.

**Comment by lorenzofelletti** [comment]
Thank you very much! Very helpful 😄
