### ISSUE TITLE
Figure out a debugging story

### ISSUE THREAD

**Issue by overdrivenpotato** [overdrivenpotato/rust-psp#52]
`psp-gdb` somewhat works for now, but it is a hefty dependency as it requires the C toolchain to be compiled and installed. It also does not support printing Rust types.

**Comment by sajattack** [comment]
I tried updating to a modern GDB and uncovered the reason it doesn't work. PSPLink's GDB Server is missing some essential thread management packet commands.

**Comment by sajattack** [comment]
Debugging is documented briefly in the readme and will soon be documented in the book. The psplink issues referred to above have been resolved.
