### ISSUE TITLE
System Libraries Needed

### ISSUE THREAD

**Issue by NT-Bourgeois-Iridescence-Technologies** [overdrivenpotato/rust-psp#6]
# TODO List
- [x] atrac3 
- [x] audio 
- [X] ctrl
- [X] display
- [X] ge
- [x] gu
- [x] gum 
- [x] hprm
- [x] jpeg
- [ ] kernel - In Progress
- [x] mp3
- [x] mpeg 
- [x] nand 
- [x] net
- [x] openpsid 
- [x] power
- [x] registry
- [x] rtc 
- [x] sircs
- [x] umd
- [x] usb
- [x] usbCam
- [x] usbstor
- [ ] user - In Progress
- [x] utility
- [x] vfpu
- [x] video
- [x] wlan 

# TO (probably not) DO List
- [ ] vsh

**Comment by overdrivenpotato** [comment]
Closing this as we have reached user-mode parity. A tracking issue now also exists for kernel mode support.
